/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.48
 * Generated at: 2025-11-14 07:36:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1762795304110L));
    _jspx_dependants.put("jar:file:/D:/EclipseWorkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Lab2_TV00062_JAV101/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664428278000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>LAB 2: Menu Điều Hướng</title>\r\n");
      out.write("    <style>\r\n");
      out.write("    .container {\r\n");
      out.write("        display: flex; \r\n");
      out.write("        flex-wrap: wrap; \r\n");
      out.write("        justify-content: space-around; \r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    .menu{\r\n");
      out.write(" 		display: flex; \r\n");
      out.write("        flex-wrap: wrap; \r\n");
      out.write("        justify-content: space-around;\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("    \r\n");
      out.write("    }\r\n");
      out.write("        body { font-family: Arial, sans-serif; line-height: 1.6; padding: 20px; }\r\n");
      out.write("        .menu-link { \r\n");
      out.write("            display: block; \r\n");
      out.write("            margin: 10px 0; \r\n");
      out.write("            padding: 12px 15px; \r\n");
      out.write("            border: 1px solid #007bff; \r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            text-decoration: none; \r\n");
      out.write("            color: #007bff; \r\n");
      out.write("            background-color: #f4f8ff;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("        .menu-link:hover { \r\n");
      out.write("            background-color: #007bff; \r\n");
      out.write("            color: white; \r\n");
      out.write("        }\r\n");
      out.write("      \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div class = \"Tieude\">\r\n");
      out.write("	\r\n");
      out.write("		<h1>LAB 2: MENU CÁC BÀI TẬP</h1>\r\n");
      out.write("	    <p>Chọn bài tập bạn muốn kiểm tra:</p>\r\n");
      out.write("	    \r\n");
      out.write("	</div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"menu\">\r\n");
      out.write("        <a href=\"sharer\" class=\"menu-link\">Bài 1: Truyền Dữ Liệu Cơ Bản (SharerServlet)</a>\r\n");
      out.write("        <a href=\"user\" class=\"menu-link\">Bài 2: Sử Dụng jsp:include (UserServlet)</a>\r\n");
      out.write("        <a href=\"form/update\" class=\"menu-link\">Bài 3 & 4: Form & JavaBean (FormServlet)</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <hr>\r\n");
      out.write("<div class =\"container\">\r\n");
      out.write("    <div class=\"item\">\r\n");
      out.write("        ");
      String _jspx_temp0_url = "item.jsp";
      String _jspx_temp0_requestEncoding = request.getCharacterEncoding();
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, _jspx_temp0_url + ((_jspx_temp0_url).indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("name", _jspx_temp0_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Fontend", _jspx_temp0_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("img", _jspx_temp0_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("anh2.png", _jspx_temp0_requestEncoding), out, false);
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"item\">\r\n");
      out.write("        ");
      String _jspx_temp1_url = "item.jsp";
      String _jspx_temp1_requestEncoding = request.getCharacterEncoding();
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, _jspx_temp1_url + ((_jspx_temp1_url).indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("name", _jspx_temp1_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Dev", _jspx_temp1_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("img", _jspx_temp1_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("anh3.png", _jspx_temp1_requestEncoding), out, false);
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"item\">\r\n");
      out.write("        ");
      String _jspx_temp2_url = "item.jsp";
      String _jspx_temp2_requestEncoding = request.getCharacterEncoding();
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, _jspx_temp2_url + ((_jspx_temp2_url).indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("name", _jspx_temp2_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Leader", _jspx_temp2_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("img", _jspx_temp2_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("anh4.png", _jspx_temp2_requestEncoding), out, false);
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"item\">\r\n");
      out.write("        ");
      String _jspx_temp3_url = "item.jsp";
      String _jspx_temp3_requestEncoding = request.getCharacterEncoding();
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, _jspx_temp3_url + ((_jspx_temp3_url).indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("name", _jspx_temp3_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Backend", _jspx_temp3_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("img", _jspx_temp3_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("anh7.jpg", _jspx_temp3_requestEncoding), out, false);
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("     <div class=\"item\">\r\n");
      out.write("        ");
      String _jspx_temp4_url = "item.jsp";
      String _jspx_temp4_requestEncoding = request.getCharacterEncoding();
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, _jspx_temp4_url + ((_jspx_temp4_url).indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("name", _jspx_temp4_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Tester", _jspx_temp4_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("img", _jspx_temp4_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("anh8.jpg", _jspx_temp4_requestEncoding), out, false);
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"item\">\r\n");
      out.write("        ");
      String _jspx_temp5_url = "item.jsp";
      String _jspx_temp5_requestEncoding = request.getCharacterEncoding();
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, _jspx_temp5_url + ((_jspx_temp5_url).indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("name", _jspx_temp5_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Admin", _jspx_temp5_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("img", _jspx_temp5_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("anhnen.jpg", _jspx_temp5_requestEncoding), out, false);
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
